name: Bulk Excel Converter for Windows

on:
  push:

jobs:
  build-windows:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install Requirements
        run: |
          pip3 install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python3 -m PyInstaller bulk_excel_to_pdf.spec
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)    
      - uses: actions/upload-artifact@v2
        with: 
          name: windows_bulkexcel
          path: dist/bulk_excel_to_pdf.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.sha }}
          release_name: ${{ github.event.head_commit.message }}
          overwrite: true
          body: |
            Bulk Excel-to-PDF Converter v1.0
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/bulk_excel_to_pdf.exe
          asset_name: bulk-excel-to-pdf-converter-windows-64bit.exe
          asset_content_type: application/zip
      
